Installing and running instructions
nesbox/TIC-80 pull request #1464
Opened 2021-06-20 15:16 UTC by vorblen

This PR adds documentation on installing and running TIC-80 using the Linux build instructions.

The original docs didn't mention running `sudo make install` to install the program.`make -j4` is executed while running `sudo make install -j4`  so the former is redundant and has been removed.The docs also didn't mention how to run the program after installation so those instructions have been added as well.

The `make -j4` in the Mac build instructions could also be replaced with `sudo make install -j4` but I don't have a MacOS machine to test it on so somebody else could try that.

2021-06-28 00:22 UTC, DannyCork approved these changes

2021-06-28 00:54 UTC, RobLoach commented
This is underneath "Build instructions", which would imply it's instructions how to build TIC-80, not install it.

2021-06-29 14:21 UTC, nesbox requested changes
Hi, 
pls move `sudo make install` to the `Install` section
Thank you for the help

2021-06-29 21:28 UTC, Voklen commented
I created an "Install instructions" section and a "Linux" sub-section to allow contributers to add install instructions for other platforms as well. I also added links to the section from the Linux build instructions.

2021-06-30 08:46 UTC, nesbox approved these changes
thank you

2021-06-30 08:46 UTC, merged