Add Shift+Return shortcut to the code editor that adds a matching "end"
nesbox/TIC-80 pull request #1721
Opened 2021-12-06 17:10 UTC by blinry

This is a convenience feature shamelessly stolen from PICO-8: when pressing Shift+Return in the code editor, insert an `end` statement, and put the cursor in an indented line in-between. For example, we go from

     for x=0,239 do|

to

    for x=0,239 do
     |
    end

I would love to use this during speedcoding! Is this a welcome feature? Does this PR look alright?

2021-12-06 17:57 UTC, nesbox requested changes

2021-12-06 17:57 UTC, nesbox commented on src/studio/editors/code.c
> +static void newLineWithEnd(Code* code)
TIC-80 also supports other scripts langs like JS, Squirrel, Wren, Fennel, and Moonscript. Please add the function "end" depending on lang, you can define it in `tic_script_config` struct (for example `const char* end = tic_core_script_config(tic)->functionEnd;`).
Thank you.

2021-12-11 17:48 UTC, nesbox commented
Any progress here?

2021-12-16 22:16 UTC, blinry commented
Good point about the multiple langs! I called the struct entry `blockEnd`, because it could also be used to close if statements and for loops, for example.

For Lua and Ruby, it's `end`, for JS, Squirrel and Wren, it's `}`, and Moon and Fennel just insert an indented line for now.

Ready for review again! :)

2021-12-17 11:04 UTC, nesbox approved these changes
Looks good, thank you 👍

2021-12-17 11:04 UTC, merged