Code Editor upgrades: structured s-expresion edition and emacs-mode
nesbox/TIC-80 pull request #2117
Opened 2023-02-05 18:43 UTC by sthilaid

Hi! This pull request adds two main features:

- Structured edition -
This functionality mimics some functionality provided by the great paredit-mode in emacs. It helps s-expression (lisp like language code structure) edition by giving you tools to create / remove expressions and enforces (to a certain extent) the balance of parenthesis. It is still missing an automatic code alignment, but this might come in later. 

- emacs-mode -
This code editor mode changes a lot of bindings to be a lot more compatible with emacs users. It also brings some new features like deleteLine, startLine and some modified functionnality for others. It also fixes what I believe is a bug in endLine (which before the fix would bring you to the end of the code buffer). To enable this, I added a new submenu called Code Editor Options which has this "emacs mode" option embeded.

- tic_script_config additions -
I added options in the language config to customize the isalnum function used when parsing their code. For instance, scheme allows a lot of normally forbidden characters in their symbols (stuff like ':' or '#'). This allows any language to customize it. In a similar fashion, there is also an option to override the API function names for that language so that the code highlight will correctly recognize them if they were modified for that language (for example, if there is a prefix). Finally, there is an option to enable structured edition for that language.

Let me know what you think!

2023-02-05 22:33 UTC, AlecTroemel commented
@sthilaid what are your thoughts moving the cursor to the inner s-expression  `ctrl-down`? I havent done much "structural editing", but It was surprising to not be able to undo a `sexpify` without first hitting `right`.

2023-02-05 22:34 UTC, AlecTroemel commented
oh also, would we be able to add quotations `"` to the list of "can only delete if the innards are cleared"?

2023-02-05 22:40 UTC, sthilaid commented
@AlecTroemel, very good suggestions, i'm going to implement both of those right away!

2023-02-06 03:14 UTC, sthilaid commented
done and done! it was a bit more work to add the double quotes to structured edition but it was an involuntary omition on my end! good catch! From my tests, it seems to be working well, hopefully there isn't too many holes in my logic.

2023-02-06 08:51 UTC, nesbox requested changes

2023-02-06 08:51 UTC, nesbox commented on src/studio/config.c
> +            .emacsMode      = false,
Could you pls move all the emacs mode declarations under `#if defined(BUILD_EDITORS)` definition, which will allow not including this option for special builds without editors?

2023-02-06 08:51 UTC, nesbox commented on src/studio/screens/mainmenu.c
> +    {"CODE EDITOR OPTIONS", showCodeEditorMenu},
The same here, pls wrap the option declaration with `#if defined(BUILD_EDITORS)`

2023-02-06 08:51 UTC, nesbox commented on src/studio/system.h
> +        bool emacsMode;
And here, please :)

2023-02-06 17:19 UTC, sthilaid commented
There seems to be some issues with the actions today, I don't know how to resolve these problems. For instance:
```Err:1 http://archive.ubuntu.com/ubuntu bionic/main amd64 fonts-lato all 2.0-2
  Connection failed [IP: 185.125.190.39 80]```

2023-02-06 18:43 UTC, sthilaid commented
lol, okay that worked... seems like the build action or not super reliable! ;p

2023-02-06 20:18 UTC, nesbox approved these changes
Seems everything looks good
Thank you

2023-02-06 20:19 UTC, merged

2023-02-06 20:38 UTC, sthilaid commented
I would like to add some documentation about these changes, when should I modify the wiki to explain them. When will version 1.1 be released? (no point in adding the doc if it's not in the users' hands)

2023-02-06 22:30 UTC, sogaiu commented
I was looking at [this](https://github.com/nesbox/TIC-80/projects/6).

2023-02-07 19:02 UTC, nesbox commented
Yes, GitHub Issues is our roadmap, 
as for adding documentation, pls create a new page in the Wiki and add a link to it on the Code Editor page https://github.com/nesbox/TIC-80/wiki#code-editor

2023-02-08 01:13 UTC, sthilaid commented
Excellent, I added the info to the wiki, thanks!

2026-01-10 21:03 UTC, blinry commented
Hello! @sthilaid, is the structured editing currently documented somewhere in the wiki? The closest I could find are the [Emacs mode hotkeys](https://github.com/nesbox/TIC-80/wiki/Hotkeys#emacs-mode). But I'm really curious about the s-expression editing features you implemented in this PR!

2026-01-10 21:56 UTC, sthilaid commented
They are not, but they don't have hotkeys. It just changes the behavior of
the other Emacs style bindings, like paredit does on Emacs.

For example, CTL+k will kill the current s-exp, or alt+f will move forward
to the end of the current s-exp.

I haven't toyed with the TIC in a while so I don't remember the extend of
my implementation but I think it covers the basics.

Let me know what your think :)

On Sat, Jan 10, 2026, 16:03 blinry ***@***.***> wrote:

> *blinry* left a comment (nesbox/TIC-80#2117)
> <https://github.com/nesbox/TIC-80/pull/2117#issuecomment-3733550870>
>
> Hello! @sthilaid <https://github.com/sthilaid>, is the structured editing
> currently documented somewhere in the wiki? The closest I could find are
> the Emacs mode hotkeys
> <https://github.com/nesbox/TIC-80/wiki/Hotkeys#emacs-mode>. But I'm
> really curious about the s-expression editing features you implemented in
> this PR!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/nesbox/TIC-80/pull/2117#issuecomment-3733550870>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAOQCCGWIW7X44DGCCTL4L4GFSLTAVCNFSM6AAAAACRJMCMUKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZTOMZTGU2TAOBXGA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>
David