Add openSUSE instructions and refactor README
nesbox/TIC-80 pull request #2712
Opened 2024-10-24 19:00 UTC by fentras

This pull request closes #2711 and also refactors the _README_ file according to these changes:

- Fixed uneven spacing and indentation
- Updated hyphens to em dashes where applicable
- Capitalized titles
- Removed `https://` from link titles
- Updated the headers structure and table of contents
- Updated _Install Instructions_ to include a no-installation method

2024-10-29 19:32 UTC, nesbox commented on README.md
> -make -j4
I think we need this command to build binaries, or we can use `cmake --build . --parallel` instead

2024-10-29 19:33 UTC, nesbox requested changes
Hi, we need `make` command or `cmake --build . --parallel`

2024-10-31 07:07 UTC, fentras commented
> Hi, we need `make` command or `cmake --build . --parallel`

Yeah, I removed `make -j4` since the command was already in the *Install Instructions* section but I didn't notice the *Arch* section missing another `cmake` command. Will fix that right now.

2024-11-11 13:28 UTC, nesbox approved these changes
Thank you

2024-11-11 13:28 UTC, merged