update pocketpy from v1.x to v2.0.1
nesbox/TIC-80 pull request #2714
Opened 2024-11-05 09:07 UTC by PrimedErwin

Modified src\api\python.c

All apis tested.

2024-11-05 09:55 UTC, blueloveTH requested changes

2024-11-05 09:55 UTC, blueloveTH commented on src/api/python.c
> +#include "pocketpy/objects/base.h"
DO NOT include internal headers.

2024-11-05 09:55 UTC, blueloveTH commented on src/api/python.c
> +struct names
Please keep the old name `CachedNames`.

2024-11-05 09:55 UTC, blueloveTH commented on src/api/python.c
> +static bool pkpy_setglobal_2(const char* name)
Delete useless function.

2024-11-05 09:55 UTC, blueloveTH commented on src/api/python.c
> +static bool get_core(tic_core** core)
Change this function to `tic_core* get_core()` and it must return a valid pointer.

2024-11-05 09:55 UTC, blueloveTH commented on src/api/python.c
> +    py_newint(py_retval(), (py_i64)core);
Use `py_r0()` instead of `py_retval()`.

2024-11-05 09:55 UTC, blueloveTH commented on src/api/python.c
> +        int list_len = py_list_len(index);
Call `py_checktype(..., tp_list)` before using any function of list.

2024-11-06 02:39 UTC, blueloveTH commented on src/api/python.c
> +    py_Ref res = (py_Ref)malloc(sizeof(py_Ref)*7);
This is incorrect.

2024-11-06 10:51 UTC, blueloveTH commented on src/api/python.c
>      py_newint(tmp, pos.x);
Use one line instead of two.
```c
py_newint(py_tuple_getitem(0), pos.x)
```

2024-11-07 10:07 UTC, blueloveTH requested changes
Should take a look at `CMakeLists.txt`.

2024-11-08 12:14 UTC, blueloveTH approved these changes

2024-11-11 13:29 UTC, nesbox approved these changes
Thank you

2024-11-11 13:29 UTC, merged